/**
 * @file strings.ts
 * @description Centralized UI string constants for UI v2 and legacy fallbacks.
 */

/**
 * UI Latest Design String Constants (Extracted from Figma UI)
 */
export const UI_STRINGS = {
  BRAND: {
    NAME: '여로',
    SLOGAN: '당신의 여행을 데이터로 그리다,',
  },
  AUTH: {
    SUB_TITLE: '당신의 여행을 데이터로 그리다,',
    MAIN_TITLE: '여로',
    GOOGLE_BUTTON_TEXT: 'Google 계정으로 계속하기',
    APPLE_BUTTON_TEXT: 'Apple 계정으로 계속하기',
    MISSING_AUTH_CODE_ERROR: '인증 코드가 누락되었습니다.',
    MISSING_APPLE_CODE_ERROR: 'Apple 인증 코드가 누락되었습니다.',
    GOOGLE_LOGIN_FAIL_DEFAULT:
      'Google 로그인에 실패했습니다. 다시 시도해 주세요.',
    APPLE_LOGIN_FAIL_DEFAULT:
      'Apple 로그인에 실패했습니다. 다시 시도해 주세요.',
    LOGIN_ERROR_TITLE: '로그인 오류',
  },
  HOME: {
    RECOMMENDED_TITLE: '추천 여행 코스',
    CREATE_COURSE_BTN: '코스 생성',
    MY_TASTE_BTN: '나의 취향',
    GUEST: '게스트',
    HONORIFIC_NIM: '님',
    GREETING_SUBTITLE: '오늘은 어디로 떠나볼까요?',
    QUICK_CREATE_COURSE: '코스 생성하기',
    QUICK_EXPLORE_COURSES: '코스 둘러보기',
    QUICK_MY_TASTE: '내 여행 취향',
    RECENT_COURSE_TITLE: '최근 확인한 여행 코스',
    DEFAULT_COURSE_TITLE: '여행 코스',
    DEFAULT_COURSE_META: '대한민국 • 일정',
    BOOKING_SECTION_TITLE: '여행 예약',
    BOOKING_PARTNER_SOURCE: 'Trip.com',
    BOOKING_FLIGHT: '항공',
    BOOKING_HOTEL: '숙소',
    BOOKING_TRAIN: '기차',
    BOOKING_TICKET: '투어·티켓',
  },
  INTRO: {
    MAIN_TITLE: '여로가 당신의\n여행을 설계합니다',
    SUB_TITLE:
      'AI가 당신의 취향을 분석하고,\n세상에 단 하나뿐인 여행 코스를 만들어요.',
    NEXT_BUTTON: '다음으로',
    SLIDE_0_CARD_1_TITLE: 'AI 취향 분석',
    SLIDE_0_CARD_1_DESC: '몇 장의 사진으로 발견하는 나만의 여행 취향',
    SLIDE_0_CARD_2_TITLE: '맞춤 코스 생성',
    SLIDE_0_CARD_2_DESC: '동선과 운영 시간을 계산한 최적의 일정 설계',
    SLIDE_0_CARD_3_TITLE: '코스 공유',
    SLIDE_0_CARD_3_DESC: '나만의 여행 코스를 친구와 공유하고 즐기기',
    SLIDE_1_BADGE_1: '🌿 자연/힐링',
    SLIDE_1_BADGE_2: '🌊 오션뷰',
    SLIDE_1_BADGE_3: '📸 감성사진',
    SLIDE_1_PROGRESS_TITLE: '취향 분석 중...',
    SLIDE_1_PROGRESS_PERCENT: '65%',
    SLIDE_1_PROGRESS_SUBTEXT: '342장의 사진 데이터 파싱 완료',
    SLIDE_2_BADGE_TEXT: '나만을 위한 최적의 여행 경로 탐색 중',
  },
  MBTI: {
    MAIN_TITLE: '당신의 MBTI는\n무엇인가요?',
    SUB_TITLE: 'MBTI를 알려주시면 성향에 맞는 여행 코스를 추천해드려요.',
    NEXT_BUTTON: '다음으로',
    ACCURATE_RECOMMEND_BUTTON: '더 정확한 추천 받기',
  },
  PHOTO_CONSENT: {
    MAIN_TITLE: '사진으로\n취향을 읽어볼까요?',
    SUB_TITLE:
      '당신의 사진을 분석하여 여행 성향을 파악해요.\n사진 원본은 외부로 전송되지 않아요.',
    CARD_1_TITLE: '메타데이터만 안전하게 가공',
    CARD_1_DESC:
      '사진 좌표와 시간 데이터만 추출하여 활용하며\n실제 사진 파일은 서버에 저장되지 않습니다.',
    CARD_2_TITLE: '분석 즉시 데이터 파기',
    CARD_2_DESC:
      'AI 취향 분석을 위한 연산 처리가 완료되는\n즉시 메타데이터는 영구 소멸됩니다.',
    START_BUTTON: '동의하고 시작하기',
  },
  TASTE_ANALYSIS: {
    MAIN_TITLE: '취향 분석 중',
    SUB_TITLE: '당신의 성향을 파악하고 있어요.',
    STEP_TITLE: '분석 단계',
    STEP_1: '사진 데이터 수집 완료',
    STEP_2: '장소 정보 수집 완료',
    STEP_3: '사용자 취향 분석 완료',
    INSIGHTS_TITLE: '실시간 분석 데이터',
    INSIGHTS_BADGE: '수집 중',
    DEFAULT_INSIGHT_MESSAGE: '실시간 가공 데이터를 처리하고 있습니다.',
    ERROR_CARD_TITLE: '사진 분석 오류',
    PERMISSION_ERROR: '사진 접근 권한이 필요합니다.',
    NO_PHOTOS_ERROR: '분석할 사진이 존재하지 않습니다.',
    NO_EXIF_ERROR: '사진 메타데이터 추출에 실패했습니다.',
  },
  TASTE_LABELS: {
    PACING: '여정 속도',
    PACE: '여정 속도',
    ACTIVITY: '활동 스타일',
    SPENDING: '소비 성향',
    COMPANION: '동행자 스타일',
    PURPOSE: '여행 목적',
    PURPOSES: '여행 목적',
    LOCATION: '선호 지역',
    FOOD: '선호 음식',
    FOODS: '선호 음식',
    SEASON: '선호 계절',
    SPACES: '좋아하는 공간',
    THEME: '여행 테마',
  },
  TASTE_PROFILE: {
    MAIN_TITLE: '당신의 여행 취향',
    PACING_LABEL: 'PACING',
    ACTIVITY_LABEL: 'ACTIVITY',
    SEASON_LABEL: 'SEASON',
    PURPOSES_TITLE: 'RANKED PURPOSES',
    FOODS_TITLE: 'FAVORITE FOODS',
    SPACES_TITLE: 'BEST SPACES',
    GENERATE_COURSE_BUTTON: '여행 코스 생성하기',
    ERROR_LOAD_FAILED: '취향 프로필을 불러오지 못했습니다.',
    EMPTY_PURPOSES: '등록된 여행 목적 정보가 없습니다.',
    EMPTY_FOODS: '등록된 음식 취향 정보가 없습니다.',
    EMPTY_SPACES: '등록된 선호 공간 정보가 없습니다.',
    TASTE_LABELS: {
      PACING: '여정 속도',
      PACE: '여정 속도',
      ACTIVITY: '활동 스타일',
      SPENDING: '소비 성향',
      COMPANION: '동행자 스타일',
      PURPOSE: '여행 목적',
      PURPOSES: '여행 목적',
      LOCATION: '선호 지역',
      FOOD: '선호 음식',
      FOODS: '선호 음식',
      SEASON: '선호 계절',
      SPACES: '좋아하는 공간',
      THEME: '여행 테마',
    },
  },
  COURSE_CREATE: {
    MAIN_TITLE: '코스 생성',
    SUB_TITLE: '당신만의 여행 코스를 만들어 드릴게요.',
    HEADER_TITLE: '코스 생성',
    SUBTITLE: '당신만의 여행 코스를 만들어 드릴게요.',
    BADGE_TEXT: '여행 정보 입력',
    DESTINATION_TITLE: '어디로 떠나시나요?',
    COUNTRY_LABEL: '여행 국가',
    COUNTRY_PLACEHOLDER: '예: 일본',
    CITY_LABEL: '여행 도시',
    CITY_PLACEHOLDER: '예: 도쿄',
    POPULAR_TITLE: '인기 여행지',
    DATE_TITLE: '언제 떠나시나요?',
    START_DATE_LABEL: '출발일',
    START_DATE_PLACEHOLDER: 'YYYY-MM-DD',
    END_DATE_LABEL: '도착일',
    END_DATE_PLACEHOLDER: 'YYYY-MM-DD',
    STYLE_TITLE: '어떤 스타일의 여행인가요?',
    BUDGET_LABEL: '여행 예산 스타일',
    STYLE_BUDGET: '가성비',
    BUDGET_COST_EFFECTIVE: '가성비',
    STYLE_MODERATE: '적정 수준',
    BUDGET_STANDARD: '적정 수준',
    STYLE_LUXURY: '럭셔리',
    BUDGET_LUXURY: '럭셔리',
    SUBMIT_BUTTON: '여행 코스 생성하기',
  },
  COURSE_GENERATING: {
    MAIN_TITLE: '당신만을 위한 여행 코스 생성 중',
    SUB_TITLE: '여정이 완성되기까지 조금만 기다려주세요.',
    STEP_1: '사용자 취향 불러오기',
    STEP_2: '여행 코스 생성 중',
    PROGRESS_LABEL: '코스 조합 중',
    BOTTOM_DESC_1: '잠시만 기다려주세요.',
    BOTTOM_DESC_2: 'AI가 여로를 그리고 있어요.',
    ERROR_TITLE: '코스 생성 중 오류가 발생했습니다',
    GO_INTRO_BTN: '시작 화면으로 이동',
    RETRY_BTN: '다시 시도하기',
  },
  COURSE_DETAIL: {
    MAIN_TITLE: '일본 도쿄',
    SUB_TITLE: '26.07.15~26.07.18 예술과 야경을 즐기는 여정',
    DAY_PREFIX: 'Day ',
    FLIGHT_BANNER_TITLE: '✈️ Trip.com 항공권 예약',
    FLIGHT_BANNER_DESC: 'Trip.com에서 항공권 예약하기',
    HOTEL_BANNER_TITLE: '🏨 Trip.com 숙소 예약',
    HOTEL_BANNER_DESC: 'Trip.com에서 숙소 예약하기',
    BOOK_NOW: '예약하기 →',
    TOTAL_BUDGET_LABEL: '총 예상 경비',
    TOTAL_BUDGET_VALUE: '₩78,000',
    FREE_TRANSIT: '교통비 무료',
    MINUTES_SUFFIX: '분 소요',
    NO_INFO: '정보 없음',
    ERROR_TITLE: '코스 상세 조회 오류',
    BOOKING_ERROR_TITLE: '오류',
    BOOKING_ERROR_MESSAGE:
      '예약 페이지를 열 수 없습니다. 잠시 후 다시 시도해주세요.',
    MAP_LOADING: '지도를 불러오는 중...',
  },
  PLACE_DETAIL: {
    DEFAULT_NAME: '모리 미술관',
    DEFAULT_CATEGORY: '관광명소',
    DEFAULT_RATING: '4.5',
    DEFAULT_ADDRESS: '도쿄도 미나토구 롯폰기 6-10-1 롯폰기힐즈 모리타워 53F',
    DEFAULT_TIME: '10:00 AM',
    DEFAULT_STAY: '90분 소요',
    DEFAULT_COST: '₩18,000',
    BUSINESS_HOURS_TITLE: '영업 시간',
    OPENING_STATUS: '영업중',
    OPENING_HOURS: '10:00 - 22:00',
    MORE_BUTTON: '더보기 ▾',
    AI_RECOMMEND_TITLE: 'AI 추천',
    AI_RECOMMEND_DESC:
      '오전 10시~11시는 관람객이 적어 여유롭게 감상할 수 있어요. 52층 전망대 통합권(₩2,300)을 구매하면 도쿄 시내 전경을 한눈에 볼 수 있고, 맑은 날에는 후지산도 보여요.',
    LOCATION_TITLE: '위치',
    GPS_LABEL: 'GPS: 35.6605, 139.7292',
    MODAL_TITLE: '영업 시간',
    TODAY_BADGE: '오늘',
  },
  COURSE_LIST: {
    COMPACT_CTA_TITLE: '새로운 맞춤형 일정이 필요할 땐?',
    CREATE_NEW_BUTTON: '새 코스 생성',
    SEARCH_PLACEHOLDER: '여행 코스 검색',
    EMPTY_TITLE: '아직 저장된 코스가 없어요',
    EMPTY_SUBTITLE: 'AI가 추천하는 맞춤 여행 코스를 생성해보세요',
    DELETE_MODAL_TITLE: '코스를 삭제하시겠습니까?',
    DELETE_MODAL_DESC: '삭제된 코스는 복구할 수 없습니다.',
    DELETE_MODAL_CONFIRM: '삭제하기',
    DELETE_MODAL_CANCEL: '취소',
    ERROR_DEFAULT: '코스 목록을 불러오지 못했습니다.',
    LOADING_TEXT: '코스 목록을 불러오는 중...',
    RETRY_BUTTON: '다시 시도',
    SEARCH_EMPTY_TITLE: '검색 결과가 없습니다',
    SEARCH_EMPTY_SUBTITLE_PREFIX: "'",
    SEARCH_EMPTY_SUBTITLE_SUFFIX: "'에 일치하는 코스가 없습니다.",
  },
  PROFILE: {
    MAIN_TITLE: '프로필',
    DEFAULT_USER_NAME: '사용자',
    EDIT_BUTTON: '수정',
    AI_TASTE_TITLE: 'AI 여행 취향 분석',
    AI_TASTE_DESC:
      'AI가 분석한 나의 독창적인 여행 스타일과 성향 키워드를 확인해보세요!',
    VIEW_TASTE_BUTTON: '나의 취향 보기',
    REANALYZE_BUTTON: '취향 재분석',
    SETTINGS_HEADER: '설정',
    SETTINGS_TITLE: '설정',
    TERMS_LABEL: '이용약관',
    TERMS_SERVICE: '이용약관',
    PRIVACY_LABEL: '개인정보 처리방침',
    TERMS_PRIVACY: '개인정보 처리방침',
    SUPPORT_LABEL: '고객 지원',
    LOGOUT_LINK: '로그아웃',
    WITHDRAW_LINK: '탈퇴하기',
    LOGOUT: '로그아웃',
    WITHDRAW: '회원 탈퇴',
    LOGOUT_CONFIRM: '로그아웃하시겠습니까?',
    WITHDRAW_NOTICE: '정말 탈퇴하시겠습니까?',
    LOGOUT_DESC: '로그아웃 시 세션이 종료됩니다.',
    WITHDRAW_CONFIRM: '탈퇴 시 모든 데이터가 삭제되며 복구할 수 없습니다.',
    LOGOUT_CONFIRM_BTN: '로그아웃',
    WITHDRAW_CONFIRM_BTN: '탈퇴하기',
    WITHDRAW_REASON_DEFAULT: '서비스 이용 불편',
    CONFIRM_CANCEL: '취소',
    CONFIRM_OK: '확인',
    WITHDRAW_HEADER: '회원탈퇴',
    WITHDRAW_ALERT_DESC:
      '정말 탈퇴하시겠습니까?\n모든 일정 및 회원 정보가 삭제됩니다.',
    WITHDRAW_ACTION_BTN: '탈퇴',
    SUPPORT_ALERT_TITLE: '고객 지원 문의',
    SUPPORT_ALERT_MESSAGE: (email: string) =>
      `메일 앱을 열 수 없습니다.\n아래 이메일로 직접 문의해주세요.\n\n문의처: ${email}`,
  },
  PROFILE_INPUT: {
    HEADER_TITLE: '프로필 설정',
    NICKNAME_LABEL: '닉네임 *',
    NICKNAME_PLACEHOLDER: '닉네임을 입력하세요',
    NICKNAME_ERROR_EMPTY: '닉네임을 입력해 주세요.',
    NICKNAME_ERROR_INVALID: '특수문자는 사용할 수 없습니다.',
    NICKNAME_ERROR_LENGTH: '닉네임은 2자 이상 10자 이하이어야 합니다.',
    EMAIL_LABEL: '이메일 *',
    EMAIL_PLACEHOLDER: '등록된 이메일이 없습니다',
    SAVE_BUTTON: '저장하고 계속하기',
    SKIP_BUTTON: '나중에 하기',
    SUCCESS_ALERT_TITLE: '프로필 저장',
    SUCCESS_ALERT_MESSAGE: '프로필 정보가 저장되었습니다.',
    ALERT_TITLE: '알림',
    ERROR_TITLE: '오류',
    UPDATE_FAILED_MESSAGE: '프로필 정보 수정에 실패했습니다.',
    AVATAR_ALERT_TITLE: '프로필 이미지',
    AVATAR_ALERT_MESSAGE:
      '카메라 또는 갤러리에서 프로필 사진을 변경하시겠습니까?',
    AVATAR_RESET_DEFAULT: '기본 이미지 적용',
  },
  COURSE_SHARE: {
    HEADER_TITLE: '공유된 여행 코스',
    INVITER_SHARED_SUFFIX: '님이 여행 코스를 공유했습니다',
    DEFAULT_INVITER_SHARED: '여행 코스를 공유했습니다',
    SAVE_BUTTON: '코스 저장하기',
    DECLINE_BUTTON: '거절하기',
    LOGIN_REQUIRED_TITLE: '로그인이 필요합니다',
    LOGIN_REQUIRED_DESC: '공유된 여행 코스를 저장하려면 로그인해주세요.',
    GOOGLE_LOGIN_BUTTON: 'Google 계정으로 계속하기',
    APPLE_LOGIN_BUTTON: 'Apple 계정으로 계속하기',
    SAVE_SUCCESS_TITLE: '코스 저장 완료',
    SAVE_SUCCESS_MESSAGE: '공유된 코스가 내 여정에 저장되었습니다.',
    ERROR_TITLE: '공유 링크 오류',
    INVALID_LINK_MESSAGE: '만료되었거나 유효하지 않은 공유 링크입니다.',
    ALREADY_SAVED_TITLE: '안내',
    ALREADY_SAVED_MESSAGE: '이미 저장된 코스입니다.',
    SAVE_FAILED_TITLE: '저장 실패',
    SAVE_FAILED_DEFAULT_MESSAGE: '코스 저장에 실패했습니다.',
    LOADING_TEXT: '공유된 코스를 불러오는 중...',
  },
  COMPONENTS: {
    CALENDAR_YEAR_SUFFIX: '년',
    CALENDAR_MONTH_SUFFIX: '월',
    CALENDAR_WEEKDAYS: ['일', '월', '화', '수', '목', '금', '토'],
  },
  COMMON: {
    CUSTOMER_SUPPORT_TEXT: '도움이 필요하신가요? ',
    CUSTOMER_SUPPORT_LINK: '고객 지원',
    SUPPORT_EMAIL_TITLE: '고객지원 이메일 안내',
    SUPPORT_EMAIL_FAIL_ALERT:
      '기기에서 메일 앱을 실행할 수 없습니다.\n아래 이메일 주소로 문의해 주세요:\n\n',
    SUPPORT_MAIL_DEFAULT_SUBJECT: '[여로] 고객 지원 및 문의',
    SUPPORT_MAIL_DEFAULT_BODY:
      '여로 서비스 이용 중 문의사항이나 개선 의견을 자유롭게 작성해주세요.\n\n-------------------\n',
    CONFIRM: '확인',
    CONFIRM_CANCEL: '취소',
    CANCEL: '취소',
    CLOSE: '닫기',
    NEXT: '다음',
    BACK: '이전',
  },
} as const;

export default UI_STRINGS;
