/**
 * @file strings.ts
 * @description Centralized UI string constants organized by screen domain and component domain for internationalization readiness.
 * @requirements REQ-1 ~ REQ-12
 * @functional FUN-1 ~ FUN-8
 * @author Antigravity Agent
 */

export const UI_STRINGS = {
  AUTH: {
    SUB_TITLE: '당신의 여행을 데이터로 그리다,',
    MAIN_TITLE: '여로',
    GOOGLE_BUTTON_TEXT: 'Google 계정으로 계속하기',
    LOGIN_ERROR_TITLE: '로그인 오류',
    LOGIN_ERROR_DEFAULT: 'Google 로그인에 실패했습니다.',
    MISSING_AUTH_CODE_ERROR: 'Google 인가 코드가 누락되었습니다.',
  },
  INTRO: {
    MAIN_TITLE: '여로가 당신의\n여행을 설계합니다',
    SUB_TITLE: 'AI가 당신의 취향을 분석하고,\n세상에 단 하나뿐인 여행 코스를 만들어요.',
    NEXT_BUTTON: '다음으로',
  },
  PHOTO_ANALYSIS: {
    MAIN_TITLE: '사진 데이터로\n당신의 취향을 분석해요',
    SUB_TITLE: '최근 앨범 사진의 장소와 시간 메타데이터만을 파싱하여\n선호하는 여행 스타일을 추천해 드립니다.',
    CONSENT_TEXT: '[필수] 사진 위치 및 시간 정보 활용 동의',
    START_BUTTON: '분석 시작하기',
  },
  TASTE_ANALYSIS: {
    TITLE: '취향 분석 중',
    SUBTITLE: '당신의 취향을 파악하고 있어요.',
    STEP_1: '당신을 알아가고 있어요',
    STEP_2: '여행 취향을 찾고 있어요',
    STEP_3: '여행 취향 분석 완료!',
    NO_TOKEN_ERROR: '인증 토큰이 없습니다. 다시 로그인해 주세요.',
    PERMISSION_ERROR: '취향 분석을 위해 기기 사진 라이브러리 접근 권한 동의가 필요합니다.',
    NO_PHOTOS_ERROR: '기기에 취향을 분석할 사진이 존재하지 않습니다.',
    NO_EXIF_ERROR: '기기에 취향을 분석할 만한 위치 정보(위도, 경도) 및 시간 정보가 포함된 사진이 존재하지 않습니다.',
    ERROR_TITLE: '분석 오류',
    DEFAULT_ERROR: '취향 분석 도중 오류가 발생했습니다.',
  },
  TASTE_PROFILE: {
    TITLE: '내 여행 취향 프로필',
    RE_ANALYSIS: '재분석하기',
    START_ANALYSIS: '취향 분석 시작하기',
    ERROR_NOT_FOUND: '저장된 여행 취향 분석 결과가 없습니다.',
    ERROR_LOAD_FAILED: '취향 프로필을 불러오지 못했습니다.',
  },
  HOME: {
    GREETING: '반가워요,',
    GREETING_SUBTITLE: '오늘 어떤 특별한 여행을 떠나볼까요?',
    GUEST: '여행자',
    HONORIFIC_NIM: '님!',
    RECOMMENDED_TITLE: '추천 여행 코스',
    CREATE_BUTTON: '새 맞춤 코스 만들기',
    EMPTY_COURSES: '아직 생성된 코스가 없습니다.',
    HERO_BADGE: 'AI 초개인화 엔진',
    HERO_DESCRIPTION: '여행 취향과 목적지에 맞춰 최적의 일정 및 경로를 실시간으로 설계해 드려요.',
    HERO_BUTTON: '여행 코스 생성하기',
    SECTION_TITLE: '빠른 추천 서비스',
    SHORTCUT_EXPLORE_TITLE: '코스 둘러보기',
    SHORTCUT_EXPLORE_SUB: '인기 추천 일정 탐색',
    SHORTCUT_PROFILE_TITLE: '내 여행 취향',
    SHORTCUT_PROFILE_SUB: 'AI 취향 정보 관리',
  },
  COURSE_CREATE: {
    TITLE: '맞춤 코스 생성',
    SUBTITLE: '여행 일정과 취향을 분석하여 당신만을 위한 최적의 이동 코스를 만들어 드립니다.',
    BADGE_TEXT: '여로 AI 맞춤 코스 생성',
    HEADER_TITLE: '어디로 떠나시나요?',
    COUNTRY_LABEL: '여행 국가',
    COUNTRY_PLACEHOLDER: '예: 대한민국, 일본, 프랑스',
    CITY_LABEL: '여행 도시',
    CITY_PLACEHOLDER: '예: 제주, 서울, 파리',
    START_DATE_LABEL: '출발 예정일',
    START_DATE_PLACEHOLDER: 'YYYY-MM-DD',
    END_DATE_LABEL: '도착 예정일',
    END_DATE_PLACEHOLDER: 'YYYY-MM-DD',
    BUDGET_LABEL: '예산 및 소비 취향',
    BUDGET_COST_EFFECTIVE: '가성비',
    BUDGET_STANDARD: '적정 수준',
    BUDGET_LUXURY: '럭셔리',
    SUBMIT_BUTTON: '여행 코스 생성하기',
  },
  COURSE_GENERATING: {
    TITLE: 'AI 여행 코스 생성 중',
    SUBTITLE: '당신의 취향과 이동 동선을 기반으로\n최적의 여행 경로를 짜고 있습니다.',
    BADGE_TEXT: '여로 AI 스마트 알고리즘',
    ERROR_TITLE: '코스 생성 중 오류가 발생했습니다.',
    GO_INTRO_BUTTON: '취향 분석 시작하기',
    DEFAULT_PROGRESS: '사용자 취향 프로필을 분석하고 최적의 경로를 생성 중입니다.',
    TIP_TEXT: '여로 AI가 취향 데이터, 장소 간 이동 동선, 예산 분포를 종합 분석하고 있습니다.',
  },
  COURSE_LIST: {
    TITLE: '당신의 여로',
    EMPTY_TITLE: '아직 생성된 여행 코스가 없습니다',
    EMPTY_SUBTITLE: 'AI와 함께 당신만의 특별한 여로를 설계해보세요.',
    SEARCH_PLACEHOLDER: '목적지 검색 (국가, 도시)',
    VIEW_LIST: '☰ 리스트',
    VIEW_GRID: '⊞ 그리드',
    LOADING: '여행 코스를 불러오는 중입니다...',
    ERROR_DEFAULT: '코스 목록을 불러오지 못했습니다.',
    UNAUTHORIZED_OR_DELETED: '접근 권한이 없거나 삭제된 코스입니다.',
    FIRST_CREATE_BUTTON: '첫 코스 생성하기',
    SEARCH_EMPTY_TITLE: '검색 결과가 없습니다',
    SEARCH_EMPTY_SUBTITLE_SUFFIX: '에 해당하는 목적지를 찾을 수 없습니다.',
  },
  COURSE_DETAIL: {
    TITLE: '여행 코스 상세',
    RECOMMENDED_TAG: 'AI 추천 코스',
    DAY_TITLE: '일차',
    MAP_VIEW: '지도 보기',
    MAP_LOADING: '지도 로딩 중...',
    RETRY_BUTTON: '다시 시도',
    ERROR_TITLE: '여행 코스 정보를 불러오지 못했습니다.',
    RETRY_ERROR_MESSAGE: '네트워크 연결 상태를 확인 후 다시 시도해 주세요.',
    DELETE_CONFIRM_TITLE: '코스 삭제',
    DELETE_CONFIRM_MESSAGE: '정말 이 여행 코스를 삭제하시겠습니까?',
    EMPTY_SCHEDULE: '해당 일자의 일정이 존재하지 않습니다.',
    TOTAL_ESTIMATED_COST: '총 예상 경비',
    TIME_UNSET: '시간 미정',
    NO_INFO: '정보 없음',
    TRANSPORT_WALKING: '도보',
    TRANSPORT_TRANSIT: '대중교통',
    TRANSPORT_DRIVING: '차량',
    TRANSPORT_TAXI: '택시',
    TRANSPORT_DEFAULT: '이동',
    MINUTES_SUFFIX: '분',
    STAY_SUFFIX: '체류',
    APPROX_CURRENCY: '약 ₩',
  },
  PROFILE: {
    TITLE: '내 프로필',
    LOGOUT: '로그아웃',
    WITHDRAW: '탈퇴하기',
    LOGOUT_CONFIRM: '정말 로그아웃 하시겠습니까?',
    WITHDRAW_CONFIRM: '정말 탈퇴하시겠습니까? 보관된 여행 코스가 모두 삭제됩니다.',
    WITHDRAW_REASON_DEFAULT: '사용자 요청',
    WITHDRAW_ERROR_TITLE: '회원탈퇴 오류',
    WITHDRAW_ERROR_DEFAULT: '회원탈퇴 처리 중 오류가 발생했습니다.',
    WITHDRAW_NOTICE: '회원탈퇴 안내',
    LOGOUT_DESC: '로그아웃 시 현재 세션이 종료되며 다시 로그인해야 서비스를 이용하실 수 있습니다.',
    LOGOUT_CONFIRM_BTN: '로그아웃 확인',
    WITHDRAW_CONFIRM_BTN: '탈퇴 진행',
  },
  COMPONENTS: {
    CTA_TITLE: 'AI와 함께 여로를 만들어보세요',
    CTA_SUBTITLE: '취향에 꼭 맞는 맞춤형 여행 코스를 즉시 생성합니다',
    CTA_BUTTON: '새 코스 생성하기 →',
    GENERATE_BUTTON_DEFAULT: '여행 코스 생성하기',
    NAV_HOME: '홈',
    NAV_EXPLORE: '탐색',
    NAV_CREATE: '생성',
    NAV_PROFILE: '프로필',
    PROFILE_HEADER_SUBTITLE: '나만의 맞춤형 여행 취향 데이터베이스',
    TASTE_CARD_TITLE: 'AI 여행 취향 분석',
    TASTE_CARD_SUBTITLE: '사진 데이터로 나만의 여행 취향을 발견해보세요',
    TASTE_CARD_VIEW_BUTTON: '나의 취향 보기',
    TASTE_CARD_BUTTON: '취향 분석 요청',
    SETTINGS_TITLE: '계정 및 서비스 설정',
    TERMS_SERVICE: '이용약관',
    TERMS_PRIVACY: '개인정보 처리방침',
    CONFIRM_CANCEL: '취소',
    CONFIRM_OK: '확인',
    CALENDAR_YEAR_SUFFIX: '년',
    CALENDAR_MONTH_SUFFIX: '월',
    CALENDAR_WEEKDAYS: ['일', '월', '화', '수', '목', '금', '토'] as const,
    DEFAULT_USER_NAME: '여로 여행자',
    DEFAULT_TRAVEL_KEYWORD: '여행',
    DURATION_SAME_DAY: '당일치기',
    DURATION_NIGHTS_SUFFIX: '박',
    DURATION_DAYS_SUFFIX: '일',
    CORE_KEYWORDS_TITLE: '핵심 여행 키워드',
    TRAVEL_PURPOSE_TITLE: '여행 취향 분석',
    LOCATION_PREFERENCE_TITLE: '선호 장소 유형',
    FOOD_PREFERENCE_TITLE: '음식 취향',
    SEASON_ENVIRONMENT_TITLE: '계절 및 환경 취향',
  },
  TASTE_LABELS: {
    PACE: {
      slow_stay: '느긋한 체류형',
      balanced: '균형형',
      dense_schedule: '빡빡한 일정형',
      spontaneous: '즉흥형',
      long_stay: '장기여행형',
    },
    SPENDING: {
      cost_effective: '가성비형',
      moderate: '중간 소비형',
      luxury: '럭셔리형',
    },
    COMPANION: {
      solo: '혼자 여행형',
      couple: '연인 여행형',
      friends: '친구 여행형',
      family: '가족 여행형',
      with_children: '아이 동반형',
      with_parents: '부모님 동반형',
      group: '단체 여행형',
      with_pet: '반려동물 동반형',
      social: '어울림형',
    },
    PURPOSE: {
      relaxation: '휴양/힐링',
      sightseeing: '관광 탐방',
      culturalExperience: '문화/예술',
      gourmet: '미식 탐험',
      natureExploration: '자연 탐방',
      activity: '액티비티',
      shopping: '쇼핑 선호',
      festivalEvent: '축제/이벤트',
      wellness: '웰니스/명상',
      selfDevelopment: '자기계발',
    },
    LOCATION: {
      bigCity: '대도시 선호',
      smallTownAlley: '소도시/골목',
      natureHinterland: '자연/오지',
      beachResort: '해변/휴양지',
      mountainPlateau: '산악/고원',
      historicalCity: '역사도시',
      themeParkResort: '테마파크',
      famousSpotPreferred: '유명 명소',
      hiddenSpotPreferred: '숨은 명소',
    },
    FOOD: {
      localFoodActive: '현지 음식 적극 체험',
      famousRestaurantCentered: '유명 맛집 탐방',
      streetFood: '길거리 음식',
      cafeDessert: '카페 & 디저트',
      fineDining: '파인다이닝',
      familiarFoodPreferred: '익숙한 음식 선호',
      dietaryRestriction: '식단 고려',
      sightseeingOverFood: '관광 중시',
    },
    SEASON: {
      warm_region: '따뜻한 지역',
      cold_region: '추운 지역',
      summer_resort: '여름 휴양',
      winter_sports: '겨울 스포츠',
      spring_flower_autumn_foliage: '봄꽃·가을 단풍',
      dry_weather: '건조한 날씨',
      off_season: '비수기 여행',
      peak_season: '성수기 여행',
    },
  },
  COMMON: {
    CUSTOMER_SUPPORT_TEXT: '도움이 필요하신가요? ',
    CUSTOMER_SUPPORT_LINK: '고객 지원',
    CANCEL: '취소',
    CONFIRM: '확인',
    CLOSE: '닫기',
    DELETE: '삭제',
    SAVE: '저장',
    LOADING: '로딩 중...',
    ERROR: '오류',
    NOTICE: '알림',
  },
} as const;

export default UI_STRINGS;
